name: CI

on:
  push:
    branches: ["main", "prod"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Frontend
      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Test frontend
        run: cd frontend && npm run test 

      - name: Build frontend
        run: cd frontend && npm run build

      # Backend
      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Build backend
        run: cd backend && npm run build
